### ISSUE TITLE
Expected ':'  IE11

### ISSUE THREAD

**Issue by HansVanderGucht** [smart-table/smart-table-ng#10]
Hi

When using smart-table-ng in IE11. I get following error : Expected ':'
This on following line ( from the CORE ) 

const sliceFactory = ({ page = 1, size } = { page: 1 }) => (array = []) => {
    const actualSize = size || array.length;
    const offset = (page - 1) * actualSize;
    return array.slice(offset, offset + actualSize);
};

**Comment by lorenzofox3** [comment]
IE11 does not support destructuring according to [Kangax table](http://kangax.github.io/compat-table/es6/) so you need to transpile your code to a Ecmascript version IE 11 understands (likely Ecmascript 5)

**Comment by HansVanderGucht** [comment]
In my angular app, and tsconfig, I alreade compile to es5 => is this the way to do it ?

**Comment by lorenzofox3** [comment]
I guess so, not sure with the little details you have provided (you should provide me a way to reproduce your issue). What I can tell you however is that the snippet you have provided is not es5 :)

**Comment by HansVanderGucht** [comment]
That's correct. This is when I test the app locally ( ng serve ). Maybe then it's compiling in ES6.  Is there a way to only compile yr library in ES5 ??

**Comment by HansVanderGucht** [comment]
Or can I apply a polyfill ?

**Comment by lorenzofox3** [comment]
> That's correct. This is when I test the app locally ( ng serve ). Maybe then it's compiling in ES6. Is there a way to only compile yr library in ES5 ??

To be honest, I don't know I have not used ng tools for a while, you should probably grab some info there on how to build angular app for IE11

> Or can I apply a polyfill ?

I don't think so as it is a syntax error (at least what I assume from the info you have provided).

**Comment by lorenzofox3** [comment]
any news on this one ?

**Comment by HansVanderGucht** [comment]
We are going to adapt our way of bundling. This will then compile to es5 to work with Ie11; Tnx for the info
