### ISSUE TITLE
smart-table-ng equivalent of st-select-row

### ISSUE THREAD

**Issue by sannyjacobsson** [smart-table/smart-table-ng#12]
Hi, 
Is there an equivalent of the Angular js smart-table st-select-row directive? If not, any suggestions to how to best achive similar functionality for smart-table-ng?

**Comment by lorenzofox3** [comment]
There is no. I think the solution would depend on your need and on on what is the purpose of selection. 
Do you need multi-select ? in that case a simple binding on your items would probably be sufficient.
Single select ? In that case I would wrap the items with some sort of model instances which get a service managing the selection state. 

If you provide a running example I may be able to help.

**Comment by sannyjacobsson** [comment]
Thank you for your reply. For now I only need single select. I'll look into your suggestion. Thank you for your offer to help. If I get stuck I may get back to you :-)
