### ISSUE TITLE
Sort data in the smart tables when there are null values.

### ISSUE THREAD

**Issue by SacheeCG** [smart-table/smart-table-ng#13]
Hi,
When there are null values in the data set, the smart table sorting function doesn't working properly. The null values come in between the sorted data.  Is there a way to sort out the null values display them at the top or bottom in the table without occurring in between the sorted data set?

**Comment by lorenzofox3** [comment]
you are right I am going to move this issue to [smart table sort repository](https://github.com/smart-table/smart-table-sort)
