### ISSUE TITLE
Render data which is fetched only on a button click

### ISSUE THREAD

**Issue by JeyashreeA** [smart-table/smart-table-ng#15]
From your tutorials, I am able to understand that I will have to attach the data to be rendered as a part of my provider in the component. However, my use case needs me to fetch data only after a button has been clicked (which also takes arguments based on user input). For such a case, can you provide an idea on how we can use the module? An example would be really helpful.

**Comment by lorenzofox3** [comment]
To make it simple, you can emit a new value on the observable passed to the smart table factory when the button is clicked. If you need an example, please set up a running example online

**Comment by JeyashreeA** [comment]
Sorry for the delay.

After I raised the ticket... I found your third article and from [this](https://stackblitz.com/edit/smart-table-ng-tutorial-3c?embed=1&file=src/app/app.component.html) example, I was able to get some idea on how to progress. Based on this and my own use case, I have created an example [here](https://stackblitz.com/edit/angular-mjkem3).

When I click on the fetch button, the data needs to be fetched and rendered. Initially, as indicated, the data would be an empty array.

Can you please let me know what I am doing wrong here?

**Comment by JeyashreeA** [comment]
Hi,

Just wanted to remind you on this issue...!

**Comment by lorenzofox3** [comment]
Hi, 

I have updated your [stackblitz](https://stackblitz.com/edit/angular-kbmc99). I used the **Use a service to manage data sources** pattern. 

The idea is:
* you have a service which holds the state of the data and expose any change through a Rx Subject
* Smart Table is instantiated  observing the subject
* The click handler makes the service emit a new bunch of data and any component which had subscribed (smart table in our case) will be notified
