### ISSUE TITLE
init and use of NgSmartTable add data instead of replacing

### ISSUE THREAD

**Issue by Rhobal** [smart-table/smart-table-ng#2]
Both the `init()` and `use()` functions of NgSmartTable add any new data to the existing through the splice; why is that so? I expected the new data to replace the existing records.

I did not find out if there is a way how I can reach and manipulate the underlying dataArray directly, I still have not found the data in the debugger...

Some JsDoc would go a long way to help understand the logic.

I'd be willing to contribute; how to go about it?

**Comment by lorenzofox3** [comment]
Thanks for the PR 👍
