### ISSUE TITLE
Promises verses Observables

### ISSUE THREAD

**Issue by devit** [smart-table/smart-table-ng#7]
Hi, I'm using

  "rxjs": "^6.3.2",
  "smart-table-ng": "0.0.10",

  following from your stackblitz examples if i use the Promise approach

	const providers = [{
  		provide: SmartTable,
  		useFactory: (Analytics: AnalyticsService, settings: TableState) => from(Analytics.fetchUsersPromise(), settings),
  		deps: [AnalyticsService, DefaultSettingsService]
	}];

	fetchUsersPromise(): Promise<User[]> {
    	return new Promise(resolve => {
      		setTimeout(() => resolve(users), 2000);
    	});
  	}

  	Everything works fine but if I use the Observables approach

	const providers = [{
  		provide: SmartTable,
  		useFactory: (Analytics: AnalyticsService, settings: TableState) => from(Analytics.fetchUsers(), settings),
  		deps: [AnalyticsService, DefaultSettingsService]
	}];

  	fetchUsers(): Observable<User[]> {
    	return of(users)
      	.pipe(delay(2000));
  	}

  	I'm getting the following error

  	ERROR TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.push../node_modules/rxjs/internal/util/subscribeTo.js.exports.subscribeTo (subscribeTo.js:42)
    at from (from.js:18)
    at from$1 (smart-table-ng.js:596)
    at useFactory (new-completed.component.ts:8)

**Comment by lorenzofox3** [comment]
Hello, difficult to say. 
what is your `users` variable in the `fetchUsers`  function ? Anyway it would be easier for me to help if you provide a running example. You can start for example by forking the related [stackblitz](https://stackblitz.com/edit/smart-table-ng-tutorial-2b?file=src%2Fusers%2Fusers.service.ts)

**Comment by devit** [comment]
Hi,I think it was a problem in my default-settings.service all working now, thank you.
