### ISSUE TITLE
Cannot find module 'rxjs/index'

### ISSUE THREAD

**Issue by akashtyagi40** [smart-table/smart-table-ng#8]
While importing 'SmartTableModule' in app.module.ts, I am facing below error:-

ERROR in node_modules/smart-table-ng/src/factories.d.ts(3,33): error TS2307: Cannot find module 'rxjs/index'.

**Comment by lorenzofox3** [comment]
it should come as a peer dependencies as it is often used in angular projects: so simply run 
``npm install rxjs``

**Comment by akashtyagi40** [comment]
I can see in dependencies that it require Rxjs 6.1.0 which only works with Angular 6.x. 
Can we use Angular 5 too ?

**Comment by lorenzofox3** [comment]
I am not sure rxjs is backward compatible. Try :) !

**Comment by akashtyagi40** [comment]
rxjs/index is not present in rxjs 5.x. Does that mean that Angular 5 can not be used with smart table ?

**Comment by lorenzofox3** [comment]
I think so
