### ISSUE TITLE
stFilter in ng build --prod throws error

### ISSUE THREAD

**Issue by devit** [smart-table/smart-table-ng#9]
Hi I'm getting this error in the production build ( ng b --prod ) when I use a stFilter, in a development mode everything is fine.
ERROR TypeError: o._addParentTeardownLogic is not a function

angular cli 7.0.3

    "@angular/core": "^6.1.10",
    "rxjs": "^6.3.3",
    "smart-table-ng": "0.0.10",

Thanks.

**Comment by lorenzofox3** [comment]
`_addParentTearDownLogic` is not part of smart table code. However you can already start by upgrading `smart-table-ng` to 0.0.12. If it does not fix the problem, can you please provide more info. Like the whole stacktrace etc

**Comment by devit** [comment]
Hi,
 I tried upgrading to 0.0.12 and got the following warnings in the production mode build.
  "smart-table-ng": "0.0.12",

WARNING in ./node_modules/smart-table-ng/fesm5/smart-table-ng.js
130:30-36 "export 'filter' was not found in 'smart-table-core'

WARNING in ./node_modules/smart-table-ng/fesm5/smart-table-ng.js
197:30-36 "export 'search' was not found in 'smart-table-core'

WARNING in ./node_modules/smart-table-ng/fesm5/smart-table-ng.js
237:30-35 "export 'slice' was not found in 'smart-table-core'

WARNING in ./node_modules/smart-table-ng/fesm5/smart-table-ng.js
476:36-41 "export 'table' was not found in 'smart-table-core'

WARNING in ./node_modules/smart-table-ng/fesm5/smart-table-ng.js
74:30-34 "export 'sort' was not found in 'smart-table-core'

**Comment by lorenzofox3** [comment]
mmh, I am not able to reproduce. Try to force smart-table-core peerDependy:
``npm install smart-table-core@3.0.2``.

Anyways it is just warning, it should not block your build
